export { default as Input } from "./Input.vue"
export { default as Select } from "./Select.vue"
export { default as Radio } from "./Radio.vue"
export { default as FileUpload } from "./FileUpload.vue"
export { default as Textarea } from "./Textarea.vue"
export { default as Number } from "./Number.vue"
export { default as Phone } from "./Phone.vue"