name: Deploy IhandCashier

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP di Runner
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, bcmath, pdo, pdo_mysql, fileinfo, tokenizer, ctype, xml, json, openssl, gd
          tools: composer:v2

      - name: Install Composer dependencies di Runner
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.0'

      - name: Check Node version
        run: node -v

      - name: Build frontend di Runner
        run: |
          npm install
          npm run build

      - name: Deploy to Server Basapadi via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/html/icphp
            git pull origin master
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 22
            npm install
            npm run build